# Application Configuration
spring.application.name=image-upscaler-backend

# Custom server port
server.port=8808

# Multipart upload limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Actuator configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Upscaler Custom Limits
upscaler.image.max-width=8192
upscaler.image.max-height=8192
upscaler.image.min-width=16
upscaler.image.min-height=16
upscaler.image.max-scale-factor=8
